<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'market');
define('_DB_USER_', 'admin');
define('_DB_PASSWD_', 'admin');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'kf60E3aojCeFRDrUTAfYmHVjB6t9bhXJdn7FPRkfY6jKb4f4kqtdfsxM');
define('_COOKIE_IV_', 'FGRWKKWi');
define('_PS_CREATION_DATE_', '2014-09-17');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'pv1p2tbf0UimbYp74M2YWEsOM9GGUOJF');
define('_RIJNDAEL_IV_', 'NmkvTDIZzHm8HQMXXlNtfA==');
